// <auto-generated />
using System;
using Cyber_Protect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyber_Protect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603132829_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cyber_Protect.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IncidentID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("IncidentID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Cyber_Protect.Models.Incident", b =>
                {
                    b.Property<int>("IncidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentID"));

                    b.Property<string>("AffectedSystems")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Assign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateReported")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IncidentID");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Cyber_Protect.Models.Threat", b =>
                {
                    b.Property<int>("ThreatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreatID"));

                    b.Property<int?>("IncidentID")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.HasKey("ThreatID");

                    b.HasIndex("IncidentID");

                    b.ToTable("Threats");
                });

            modelBuilder.Entity("Cyber_Protect.Models.Employee", b =>
                {
                    b.HasOne("Cyber_Protect.Models.Incident", null)
                        .WithMany("Employees")
                        .HasForeignKey("IncidentID");
                });

            modelBuilder.Entity("Cyber_Protect.Models.Threat", b =>
                {
                    b.HasOne("Cyber_Protect.Models.Incident", null)
                        .WithMany("Threats")
                        .HasForeignKey("IncidentID");
                });

            modelBuilder.Entity("Cyber_Protect.Models.Incident", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Threats");
                });
#pragma warning restore 612, 618
        }
    }
}
